---
- hosts: all
  tasks:
    - block:
      - name: Instala o apache para o Debian
        apt:
          name: apache2
          state: present
      
      - name: Iniciar o Apache
        service:
          name: apache2
          state: started

      when: ansible_distribution == 'Ubuntu'


    - block:

      - name: Instala o apache para RedHat
        yum:
          name: httpd
          state: present
      - service:
          name: httpd
          state: started
      when: ansible_distribution == 'CentOS'

    - name: Copia o conteudo do portal Dexter
      copy:
        src: index.html
        dest: /var/www/html/index.html



